# Site settings
title: Joona Lehtomäki
url: 'https://jehtoma.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'jlehtoma'

author:
  name: 'Joona Lehtomäki'
  email: joona.lehtomaki@gmail.com
  twitter_username: jlehtoma
  github_username:  jlehtoma
  linkedin_username:  jlehtoma
  researchgate_username: Joona_Lehtomaeki
  orcid_id: 0000-0002-7891-0843

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'
        is_post: true

# Build settings
destination: _site
paginate: 5
paginate_path: "/blog/page:num/"
#permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
