# Site settings
title: Joona Lehtomäki
description: 'Joona Lehtomäki'
url: 'https://jehtoma.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Joona Lehtomäki'
  email: joona.lehtomaki@gmail.com
  twitter_username: jlehtoma
  facebook_username: jlehtoma
  github_username:  jlehtoma
  linkedin_username:  jlehtoma

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 5
paginate_path: "/blog/page:num/"
#permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
